- hosts: jenkins_slaves
  sudo: true
  roles: 
    - tools
    - lv
    - config
    - user
# this play runs entirely on the host
- hosts: local
  user: yourusername
  sudo: true
  roles:
    - tools
    - lv
    - config
    - user

