---
- name: check that in .bashrc that http_proxy, https_proxy, no_proxy are set and exported for use from commandline. 
  become: yes
  shell: cat ~/.bashrc | grep 'export http_proxy'
  register: http_proxies
  ignore_errors: yes
- name: set http_proxy, https_proxy and no_proxy
  become: yes
  lineinfile: dest={{ item[1] }}
              state=present
              create=yes
              insertafter=EOF
              line={{ item[0] }}
  with_items:
  - ['export http_proxy=http://httppxgot.srv.volvo.com:8080', 'export https_proxy=https://httppxgot.srv.volvo.com:8080', 'export no_proxy=localhost,127.0.0.1,.volvo.net']
  - ['~/.bashrc', '/root/.bashrc']
  when: http_proxies.stdout.find('.volvo.com') != -1
- name: source .bashrc to set proxy environment variables
  become: yes
  shell: source ~/.bashrc
- name: install yum-utils
  become: yes
  yum: name=yum-utils
- name: check if container-selinux is installed
  become: yes
  shell:  rpm -qa | grep container-selinux
  register: cn_selinux
  ignore_errors: yes
- name: install container-selinux 2.9
  become: yes
  command: yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
  when: cn_selinux.stdout == ""
- name: docker ce stable repo
  yum_repository:
    name: 'docker-ce-stable'
    # https://stackoverflow.com/questions/42981114/install-docker-ce-17-03-on-rhel7
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    description: Docker CE Stable repo
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
#- name: setup docker CE repo
#  become: yes
#  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
- name: Ensure the yum package index is up to date
  become: yes
  yum:
    update_cache: yes
    name: '*'
    state: latest
- name: Yum update
  become: yes
  yum: name=* state=latest
- name: Install git
  become: yes
  yum: name=git
- name: Install docker
  become: yes
  yum: name=docker-ce
- name: Install docker-compose
  become: yes
  get_url: 
      url : https://github.com/docker/compose/releases/download/1.16.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
- name: Start docker
  service: name=docker state=started
  become: yes
