---
- name: Set new repos to yum docker repo
  become: yes
  lineinfile: dest=/etc/yum.repos.d/docker.repo
              state=present
              create=yes
              insertafter=EOF
              line={{ item }}
  with_items:
    - "[dockerrepo]"
    - "name=Docker Repository"
    - "baseurl=https://yum.dockerproject.org/repo/main/centos/7"
    - "enabled=1"
    - "gpgcheck=1"
    - "gpgkey=https://yum.dockerproject.org/gpg"
- name: Yum update
  become: yes
  yum: name=* state=latest
- name: Install git
  become: yes
  yum: name=git
- name: Install docker
  become: yes
  yum: name=docker-engine
- name: Install docker-compose
  become: yes
  get_url: 
      url : https://github.com/docker/compose/releases/download/1.7.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
- name: Start docker
  service: name=docker state=started
  become: yes