# Configure device mapper. 
---
- name: Check if docker starts
  become: yes
  command: docker info 
- name: Stop docker service
  become: yes
  command: systemctl stop docker
- name: check for docker.service.d directory
  become: yes
  stat: path=/etc/systemd/system/docker.service.d
  register: service_d

- name: create docker systemctl service directory
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: service_d.stat.exists == False  

- name: create docker proxy file
  become: yes
  lineinfile: dest=/etc/systemd/system/docker.service.d/http-proxy.conf
              state=present
              create=yes
              insertafter=EOF
              line="Environment='HTTP_PROXY=http://httppxgot.srv.volvo.com:8080' 'HTTPS_PROXY=http://httppxgot.srv.volvo.com:8080' 'NO_PROXY=localhost,127.0.0.1,.volvo.net'"
- name: Configure docker to use new device driver
  become: yes
  lineinfile: dest=/etc/systemd/system/docker.service.d/docker.conf
              state=present
              create=yes
              insertafter=EOF
              line={{ item }}
  with_items:
    - "[Service]"
    - "ExecStart="
    - "ExecStart=/usr/bin/dockerd --debug --storage-driver=devicemapper --storage-opt dm.thinpooldev=/dev/mapper/docker-thinpool --storage-opt dm.use_deferred_removal=true"

- name: check if /var/lib/docker is mounted
  become: yes
  shell: lsblk | grep '/home/jenkins'
  register: jenkins_home
  ignore_errors: yes
- name: remove /var/lib/docker
  become: yes
  file: path=/var/lib/docker state=absent
  when: jenkins_home.stdout == ""
- name: Mount docker-data disk to /var/lib/docker
  become: yes
  mount: 
    name: /var/lib/docker
    src: /dev/docker/docker-data
    fstype: ext4
    state: mounted
- name: Mount jenkins-home disk to the /home/jenkins
  become: yes
  mount: 
    name: /home/jenkins
    src: /dev/docker/jenkins-home
    state: mounted
    fstype: ext4

- name: Reload daemon
  become: yes
  command: systemctl daemon-reload
- name: Start docker
  become: yes
  command: systemctl start docker
